### PR TITLE
simplified setup instructions

### PR DESCRIPTION
**Pull request by yakticus**
- removed scala requirement from instructions
- new doodle.zip that doesn't include __MACOS/ dir in it

### CODE REVIEW

**Comment by robinske** [comment]
@yakticus does this still allow people to access the Scala repl without the doodle project?

**Comment by yakticus** [comment]
@robinske Admittedly, it does not. All scala REPL functions can be accessed via the doodle project, as it fires up a REPL inside it. If we want students to use the REPL stand-alone, then I can put those instructions back.

**Comment by robinske** [comment]
I'd like to leave in the install Scala part, even if the curriculum doesn't explicitly require the Scala REPL it would be nice to have just in case and for the students going forward as they explore the language on their own.

**Comment by yakticus** [comment]
Sorry I haven't had a chance to update the PR yet. Since the installfest is tomorrow I won't make such big changes before then. If it hasn't been fixed yet, I'll push a change to the zip file that removes the extra directory called `__MACOSX`, which could confuse people.

**Pull request closed without merging**
